// ===== components/enemy/enemyConfig.js =====
export const ENEMY_CONFIGS = {
  normal: {
    name: "normal",
    score: 1,
    spawnWeightStart: 80,
    spawnWeightEnd: 30,
    color: [245, 74, 74],
    size: 32,
    maxHp: 3.8,
    speed: 100,
    damage: 1,
  },

  fast: {
    name: "fast",
    score: 2,
    spawnWeightStart: 15,
    spawnWeightEnd: 22,
    color: [248, 175, 39],
    size: 28,
    maxHp: 1.9,
    speed: 180,
    damage: 1,
    hasBody: false,
    opacity: 0.7,
  },

  tank: {
    name: "tank",
    score: 3,
    spawnWeightStart: 10,
    spawnWeightEnd: 20,
    color: [100, 100, 255],
    size: 40,
    maxHp: 8,
    speed: 60,
    damage: 2,
  },

  rageTank: {
    name: "rageTank",
    score: 5,
    spawnWeightStart: 3,
    spawnWeightEnd: 8,
    color: [153, 36, 27],
    size: 36,
    maxHp: 6.8,
    speed: 60,
    damage: 2,
  },

  spawner: {
    name: "broodsquare",
    score: 4,
    spawnWeightStart: 7,
    spawnWeightEnd: 11,
    color: [106, 190, 48],
    size: 36,
    maxHp: 6,
    speed: 55,
    damage: 1,
  },

  small: {
    name: "small",
    score: 1,
    spawnWeightStart: 0, // never randomly chosen
    spawnWeightEnd: 0,
    color: [170, 215, 120],
    size: 16,
    maxHp: 1,
    speed: 140,
    damage: 1,
    hasBody: false,
    opacity: 1,
  },

  sniper: {
    name: "sniper",
    score: 4,
    spawnWeightStart: 4,
    spawnWeightEnd: 8,
    color: [30, 90, 150],
    size: 30,
    maxHp: 2.9,
    speed: 120,
    damage: 1,
  },

  miniboss: {
    name: "miniboss",
    score: 30,
    spawnWeightStart: 0,
    spawnWeightEnd: 0,
    color: [245, 245, 245],
    size: 50,
    maxHp: 40,
    speed: 75,
    damage: 2,
  },

  boss: {
    name: "boss",
    score: 50,
    spawnWeightStart: 0,
    spawnWeightEnd: 0,
    color: [60, 20, 20],
    size: 80,
    maxHp: 300,
    speed: 80,
    damage: 3,
  },
  slime: {
    name: "slime",
    score: 4,
    spawnWeightStart: 0,
    spawnWeightEnd: 5,
    color: [180, 220, 50],
    size: 38,
    maxHp: 11,
    speed: 50,
    damage: 1,
  },
  graviton: {
    name: "graviton",
    score: 8,
    spawnWeightStart: 0,
    spawnWeightEnd: 7,
    color: [10, 5, 25],
    size: 44,
    maxHp: 20,
    speed: 35,
    damage: 2,
    hasBody: false,
  },
  glitch: {
    name: "glitch",
    score: 6,
    spawnWeightStart: 0,
    spawnWeightEnd: 9,
    color: [140, 80, 200],
    size: 30,
    maxHp: 4.9,
    speed: 140,
    damage: 1,
  },
  DUMMY: {
    name: "DUMMY",
    score: 0,
    spawnWeightStart: 0,
    spawnWeightEnd: 0,
    color: [40, 40, 40],
    size: 80,
    maxHp: 400,
    speed: 40,
    damage: 0,
  },
};
